"""
Hockey Tactical Analysis System

A comprehensive system for analyzing hockey formations, tactics, and strategic patterns
from player tracking data generated by the Computer-Vision-for-Hockey project.
"""

__version__ = "1.0.0"
__author__ = "Hockey Analytics Team"

try:
    from .formation_detector import FormationDetector, RinkZone, FormationPattern
    from .zone_analyzer import ZoneAnalyzer, ZoneMetrics
    from .tactical_analyzer import TacticalAnalyzer
except ImportError:
    from formation_detector import FormationDetector, RinkZone, FormationPattern
    from zone_analyzer import ZoneAnalyzer, ZoneMetrics
    from tactical_analyzer import TacticalAnalyzer

__all__ = [
    'FormationDetector',
    'RinkZone', 
    'FormationPattern',
    'ZoneAnalyzer',
    'ZoneMetrics',
    'TacticalAnalyzer'
]
