#!/usr/bin/env python3
"""
Command-line interface for hockey tactical analysis.

This script provides an easy way to analyze hockey formations and tactics
from player tracking data generated by the Computer-Vision-for-Hockey project.
"""

import argparse
import sys
from pathlib import Path
import logging

# Add the src directory to the path so we can import our modules
sys.path.append(str(Path(__file__).parent))

from tactical_analyzer import TacticalAnalyzer

def setup_logging(verbose: bool = False):
    """Set up logging configuration."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

def main():
    """Main command-line interface."""
    parser = argparse.ArgumentParser(
        description="Analyze hockey formations and tactics from player tracking data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic formation analysis
  python analyze_formations.py data/player_tracking.json
  
  # Comprehensive analysis with custom output directory
  python analyze_formations.py data/player_tracking.json --output results/ --complete
  
  # Analyze with custom parameters
  python analyze_formations.py data/player_tracking.csv --min-frames 10 --min-confidence 0.7
  
  # Verbose output for debugging
  python analyze_formations.py data/player_tracking.json --verbose
        """
    )
    
    parser.add_argument(
        'input_path',
        help='Path to tracking data file (JSON or CSV)'
    )
    
    parser.add_argument(
        '--output', '-o',
        default='results',
        help='Output directory for analysis results (default: results/)'
    )
    
    parser.add_argument(
        '--complete', '-c',
        action='store_true',
        help='Run complete analysis including zone analysis and tactical insights'
    )
    
    parser.add_argument(
        '--min-frames',
        type=int,
        default=5,
        help='Minimum consecutive frames to confirm formation (default: 5)'
    )
    
    parser.add_argument(
        '--min-confidence',
        type=float,
        default=0.6,
        help='Minimum confidence threshold for formation detection (default: 0.6)'
    )
    
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose logging output'
    )
    
    parser.add_argument(
        '--formations',
        help='Comma-separated list of specific formations to analyze (e.g., "1-3-1,2-1-2")'
    )
    
    args = parser.parse_args()
    
    # Setup logging
    setup_logging(args.verbose)
    logger = logging.getLogger(__name__)
    
    # Validate input file
    input_path = Path(args.input_path)
    if not input_path.exists():
        logger.error(f"Input file not found: {input_path}")
        sys.exit(1)
    
    if input_path.suffix.lower() not in ['.json', '.csv']:
        logger.error(f"Unsupported file format: {input_path.suffix}")
        logger.error("Supported formats: .json, .csv")
        sys.exit(1)
    
    try:
        logger.info(f"Starting tactical analysis of {input_path}")
        
        # Initialize analyzer
        analyzer = TacticalAnalyzer(
            input_path=input_path,
            output_dir=args.output
        )
        
        if args.complete:
            # Run complete analysis
            logger.info("Running complete tactical analysis...")
            results = analyzer.run_complete_analysis()
            
            logger.info("Complete analysis finished!")
            logger.info(f"Results saved to: {args.output}")
            
            # Print summary
            print("\n" + "="*60)
            print("TACTICAL ANALYSIS COMPLETE")
            print("="*60)
            
            if results["formation_analysis"]["detected_formations"]:
                formations = results["formation_analysis"]["detected_formations"]
                print(f"\nDetected {len(formations)} formations:")
                for formation in formations[:5]:  # Show first 5
                    print(f"  • {formation['formation']} (confidence: {formation['avg_confidence']:.2f})")
                if len(formations) > 5:
                    print(f"  ... and {len(formations) - 5} more")
            
            # Print tactical summary
            if "summary" in results["tactical_insights"]:
                print(f"\nTactical Summary:")
                print(f"  {results['tactical_insights']['summary']}")
            
            # Print key recommendations
            if "strategic_recommendations" in results["tactical_insights"]:
                print(f"\nKey Recommendations:")
                for category, recommendation in results["tactical_insights"]["strategic_recommendations"].items():
                    print(f"  • {category.replace('_', ' ').title()}: {recommendation}")
            
        else:
            # Run basic formation analysis only
            logger.info("Running basic formation analysis...")
            formation_results = analyzer.analyze_formations(
                min_frames=args.min_frames,
                min_confidence=args.min_confidence
            )
            
            logger.info("Formation analysis complete!")
            
            # Print results
            print("\n" + "="*60)
            print("FORMATION ANALYSIS RESULTS")
            print("="*60)
            
            if formation_results["detected_formations"]:
                formations = formation_results["detected_formations"]
                print(f"\nDetected {len(formations)} formations:")
                
                for formation in formations:
                    print(f"\n  Formation: {formation['formation']}")
                    print(f"    Duration: {formation['duration_frames']} frames")
                    print(f"    Confidence: {formation['avg_confidence']:.2f}")
                    print(f"    Time: {formation['start_time']:.1f}s - {formation['end_time']:.1f}s")
                
                # Print statistics
                stats = formation_results["formation_statistics"]
                print(f"\nFormation Statistics:")
                print(f"  Total formations: {stats['total_formations']}")
                print(f"  Most common: {stats['most_common']}")
                
                if formation_results["transition_analysis"]["transitions"]:
                    transitions = formation_results["transition_analysis"]
                    print(f"  Total transitions: {transitions['total_transitions']}")
                    if transitions["most_common"]:
                        most_common = transitions["most_common"]
                        print(f"  Most common transition: {most_common[0]} ({most_common[1]} times)")
            else:
                print("\nNo formations detected with current parameters.")
                print("Try adjusting --min-frames or --min-confidence parameters.")
        
        print(f"\nDetailed results saved to: {args.output}")
        
    except Exception as e:
        logger.error(f"Analysis failed: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
